### ISSUE TITLE
Having trouble to ping Zerotier ip address with Mac OS

### ISSUE THREAD

**Issue by Subline-75** [ciprianiacobescu/XorValidatorRegistryUnofficial#1]
Context: trying to run the guide on my laptop.

Here is my configuration in Zerotier:
<img width="263" alt="Capture d’écran 2021-04-29 à 16 09 34" src="https://user-images.githubusercontent.com/83412467/116567156-aac78600-a907-11eb-8ed4-82e5b4564a66.png">

The machine appears online on Zerotier.

In terminal, I runned: 
ping 10.147.17.101

result: 
PING 10.147.17.101 (10.147.17.101): 
56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

I does not goes through.

Signed from: 
![image](https://user-images.githubusercontent.com/83412467/116569585-d186bc00-a909-11eb-94df-0cf3067fc638.png)
cnSmvALMdvFxSmoSUGW18aVZkVktJYYw6dYhg9pBJNwR9eazu

**Comment by ciprianiacobescu** [comment]
Are you using Windows?

**Comment by Subline-75** [comment]
> Are you using Windows?

No, I use Mac OS Catalina 10.15.7

**Comment by ciprianiacobescu** [comment]
Mac OS does not support bridge for docker networks

**Comment by Subline-75** [comment]
I have been able to ping my machine (not from my hosted serv, but from my mobile) after I disabled stealth mode option in the firewall settings.

**Comment by Subline-75** [comment]
Finally! 

I had to open port 9993 on my router & on my server, and now all machines are able to ping each other.
