### ISSUE TITLE
2 Quality Validators /  Decentralize 

### ISSUE THREAD

**Issue by fanderson3** [ciprianiacobescu/XorValidatorRegistryUnofficial#8]
Please add

These 2 Sora network validators are both operated by RICEBOWL in secured certified tier 3 99.99% uptime data centers with professional sysadmin support. See attached screen shot of updated validator stats for Ricebowl 1 in St Luis USA location for review and reference. Please include in your list so we can decentralize. 

RICEBOWL 2
cnVGC5Hj6fPrdT3FZS4cifQkZM38o5gFdGFL9i8HXc7r9Bz39 - Germany Location (**deployed 05082021 we need nominators on this server**)

RICEBOWL 1
cnUnjXnoZqE3wvzhFfRuqzdWeu21w9abji1gvGDgXMiuxTgau - USA Location

 
![Ricebowl1Sora_Stats](https://user-images.githubusercontent.com/31581979/117558184-89cf0580-b06a-11eb-8678-48ded903faea.png)

**Comment by ciprianiacobescu** [comment]
Done! Added Ricebowl 2 first. Most probably will get picked first!

**Comment by fanderson3** [comment]
Many thanks !
