### ISSUE TITLE
Can we add polkamap validators to the list

### ISSUE THREAD

**Issue by GeoScobie** [ciprianiacobescu/XorValidatorRegistryUnofficial#9]
Polkamap 1
cnVLbvxKzwgoRFgywfEfWBUMpqisivbfiZ9uHL7ZGyrrsVSZ5 
Polkamap 2
cnTteC9Z7SnoLBvKrBp7beAQPa4sSz2jf1uzBf5ZHHGRs3J1s
Polkamap 3
cnVvig3Uc74pFi14WnEkKDHxZAXKXPWsGCsg7BDMmmJqyR6X9

**Comment by ciprianiacobescu** [comment]
Done!
